name: Entrypoint
description: Entrypoint indexer v0.6 & v0.7
unordered_multichain_mode: true
contracts:
  - name: Entrypoint
    handler: ./src/EventHandlers.ts
    events:
      - event: UserOperationEvent(bytes32 indexed userOpHash, address indexed sender, address indexed paymaster, uint256 nonce, bool success, uint256 actualGasCost, uint256 actualGasUsed)
      - event: AccountDeployed(bytes32 indexed userOpHash, address indexed sender, address factory, address paymaster)
networks:
  - id: 1 # Mainnet
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 5 # Goerli
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 11155111 # Sepolia
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 56 # BSC
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 97 # BSC Testnet # hypersync not suported on bsc testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 137 # Polygon
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 80001 # Polygon Mumbai
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 1101 # Polygon ZK-EVM
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 1442 # Polygon ZK-EVM Testnet # hypersync not suported on polygon zk-evm testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 250 # Fantom
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 4002 # Fantom Testnet # hypersync not suported on fantom testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 10 # Optimism Mainnet
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 11155420 # Optimism Sepolia
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42161 # Arbitrum
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 421614 # Arbitrum Sepolia
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42170 # Arbitrum Nova
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 1285 # Moonriver # hypersync not suported on moonriver yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 1284 # Moonbeam
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 1287 # Moonbase Alpha # hypersync not suported on moonbase alpha yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 25 # Cronos # hypersync not suported on cronos yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 100 # Gnosis
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 10200 # Gnosis Chiado
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 42220 # Celo
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 44787 # Celo Alfajores # hypersync not suported on celo alfajores yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 59144 # Linea
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 59140 # Linea Testnet # hypersync not suported on linea testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 8453 # Base
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 84532 # Base Sepolia
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 534352 # Scroll
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 534351 # Scroll Sepolia # hypersync not suported on scroll sepolia yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 204 # OP BNB # hypersync not suported on op bnb yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 5611 # OP BNB Testnet # hypersync not suported on op bnb testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 255 # Kroma # hypersync not suported on kroma yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 2358 # Kroma Testnet # hypersync not suported on kroma testnet yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  - id: 43114 # Avalanche C-Chain
    start_block: 0
    contracts:
      - name: Entrypoint # A reference to the global contract definition
        address:
          - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
          - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 43113 # Avalanche Fuji Testnet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 7777777 # Zora # hypersync not suported on zora yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
  # - id: 999999999 # Zora Sepolia # hypersync not suported on zora sepolia yet
  #   start_block: 0
  #   contracts:
  #     - name: Entrypoint # A reference to the global contract definition
  #       address:
  #         - "0x5ff137d4b0fdcd49dca30c7cf57e578a026d2789"
  #         - "0x0000000071727de22e5e9d8baf0edac6f37da032"
